// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonaliPonto.Infrastructure.Persistence;

#nullable disable

namespace PersonaliPonto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonaliPontoDbContext))]
    partial class PersonaliPontoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("personaliponto")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.AncoraHora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<DateTimeOffset>("HoraServidor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_servidor");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id")
                        .HasName("pk_ancoras_hora");

                    b.ToTable("ancoras_hora", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.ArquivoArmazenado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_original");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_arquivos");

                    b.HasIndex("TenantId", "CriadoEm")
                        .HasDatabaseName("ix_arquivos_tenant_id_criado_em");

                    b.ToTable("arquivos", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .HasColumnType("text")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("text")
                        .HasColumnName("usuario_nome");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "Em")
                        .HasDatabaseName("ix_audit_logs_tenant_id_em");

                    b.ToTable("audit_logs", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Empregador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("identificador");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoIdentificador")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_identificador");

                    b.HasKey("Id")
                        .HasName("pk_empregadores");

                    b.ToTable("empregadores", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Estabelecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CnoCaepf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cno_caepf");

                    b.Property<Guid>("EmpregadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("empregador_id");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("fuso_horario");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("identificador");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocalPrestacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("local_prestacao");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("ModoCerca")
                        .HasColumnType("integer")
                        .HasColumnName("modo_cerca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int?>("RaioCercaMetros")
                        .HasColumnType("integer")
                        .HasColumnName("raio_cerca_metros");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoIdentificador")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_identificador");

                    b.HasKey("Id")
                        .HasName("pk_estabelecimentos");

                    b.HasIndex("EmpregadorId")
                        .HasDatabaseName("ix_estabelecimentos_empregador_id");

                    b.HasIndex("TenantId", "Identificador")
                        .IsUnique()
                        .HasDatabaseName("ix_estabelecimentos_tenant_id_identificador");

                    b.ToTable("estabelecimentos", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateOnly?>("DataDemissao")
                        .HasColumnType("date")
                        .HasColumnName("data_demissao");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<Guid?>("GestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("gestor_id");

                    b.Property<Guid?>("JornadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("jornada_id");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("matricula");

                    b.Property<string>("MatriculaEsocial")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("matricula_esocial");

                    b.Property<int?>("ModoCercaFuncionario")
                        .HasColumnType("integer")
                        .HasColumnName("modo_cerca_funcionario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteMarcacaoApp")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_marcacao_app");

                    b.Property<bool>("PermiteMarcacaoOffline")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_marcacao_offline");

                    b.Property<DateTimeOffset?>("PinBloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_bloqueado_ate");

                    b.Property<string>("PinHash")
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<int>("PinTentativasFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("pin_tentativas_falhas");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_funcionarios");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_funcionarios_estabelecimento_id");

                    b.HasIndex("JornadaId")
                        .HasDatabaseName("ix_funcionarios_jornada_id");

                    b.HasIndex("TenantId", "Cpf")
                        .HasDatabaseName("ix_funcionarios_tenant_id_cpf");

                    b.HasIndex("TenantId", "EstabelecimentoId", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionarios_tenant_id_estabelecimento_id_matricula");

                    b.ToTable("funcionarios", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Jornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int?>("CicloDias")
                        .HasColumnType("integer")
                        .HasColumnName("ciclo_dias");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateOnly?>("DataReferenciaCiclo")
                        .HasColumnType("date")
                        .HasColumnName("data_referencia_ciclo");

                    b.Property<string>("Horarios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("horarios");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int>("ToleranciaDiariaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tolerancia_diaria_minutos");

                    b.Property<int>("ToleranciaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tolerancia_minutos");

                    b.HasKey("Id")
                        .HasName("pk_jornadas");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_jornadas_tenant_id_codigo");

                    b.ToTable("jornadas", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.MarcacaoContexto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("DentroCerca")
                        .HasColumnType("boolean")
                        .HasColumnName("dentro_cerca");

                    b.Property<string>("DispositivoId")
                        .HasColumnType("text")
                        .HasColumnName("dispositivo_id");

                    b.Property<DateTimeOffset?>("HorarioInformadoColetor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horario_informado_coletor");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("RegistroRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_rep_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id")
                        .HasName("pk_marcacoes_contexto");

                    b.HasIndex("RegistroRepId")
                        .IsUnique()
                        .HasDatabaseName("ix_marcacoes_contexto_registro_rep_id");

                    b.ToTable("marcacoes_contexto", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.NsrContador", b =>
                {
                    b.Property<Guid>("EstabelecimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UltimoHashTipo7")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ultimo_hash_tipo7");

                    b.Property<long>("UltimoNsr")
                        .HasColumnType("bigint")
                        .HasColumnName("ultimo_nsr");

                    b.HasKey("EstabelecimentoId")
                        .HasName("pk_nsr_contadores");

                    b.ToTable("nsr_contadores", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<DateTimeOffset?>("ProximaTentativa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("ProcessadoEm", "ProximaTentativa")
                        .HasDatabaseName("ix_outbox_processado_em_proxima_tentativa");

                    b.ToTable("outbox", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.RegistroRep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("CnoCaepf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cno_caepf");

                    b.Property<int?>("Coletor")
                        .HasColumnType("integer")
                        .HasColumnName("coletor");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("CpfResponsavel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf_responsavel");

                    b.Property<DateTimeOffset?>("DataHoraAjustada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_ajustada");

                    b.Property<DateTimeOffset?>("DataHoraAntesAjuste")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_antes_ajuste");

                    b.Property<DateTimeOffset>("DataHoraGravacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_gravacao");

                    b.Property<DateTimeOffset?>("DataHoraMarcacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_marcacao");

                    b.Property<string>("DemaisDados")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("demais_dados");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("IdentificadorEmpregador")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("identificador_empregador");

                    b.Property<string>("LocalPrestacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("local_prestacao");

                    b.Property<string>("NomeEmpregado")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_empregado");

                    b.Property<long>("Nsr")
                        .HasColumnType("bigint")
                        .HasColumnName("nsr");

                    b.Property<bool?>("Offline")
                        .HasColumnType("boolean")
                        .HasColumnName("offline");

                    b.Property<int>("OffsetGravacaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("offset_gravacao_minutos");

                    b.Property<int?>("OffsetMarcacaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("offset_marcacao_minutos");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int?>("TipoEvento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_evento");

                    b.Property<int?>("TipoIdentificadorEmpregador")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_identificador_empregador");

                    b.Property<char?>("TipoOperacao")
                        .HasColumnType("character(1)")
                        .HasColumnName("tipo_operacao");

                    b.HasKey("Id")
                        .HasName("pk_registros_rep");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_registros_rep_funcionario_id");

                    b.HasIndex("EstabelecimentoId", "DataHoraGravacao")
                        .HasDatabaseName("ix_registros_rep_estabelecimento_id_data_hora_gravacao");

                    b.HasIndex("EstabelecimentoId", "Nsr")
                        .IsUnique()
                        .HasDatabaseName("ix_registros_rep_estabelecimento_id_nsr");

                    b.HasIndex("TenantId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_registros_rep_tenant_id_client_id")
                        .HasFilter("client_id IS NOT NULL");

                    b.HasIndex("TenantId", "FuncionarioId", "DataHoraMarcacao")
                        .HasDatabaseName("ix_registros_rep_tenant_id_funcionario_id_data_hora_marcacao");

                    b.ToTable("registros_rep", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailContato")
                        .HasColumnType("text")
                        .HasColumnName("email_contato");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("text")
                        .HasColumnName("telefone_contato");

                    b.Property<DateTimeOffset?>("TesteAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("teste_ate");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.TerminalWeb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UltimoUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso");

                    b.HasKey("Id")
                        .HasName("pk_terminais_web");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_terminais_web_token_hash");

                    b.ToTable("terminais_web", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Tratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("motivo");

                    b.Property<int?>("OffsetMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("offset_minutos");

                    b.Property<Guid?>("RegistroRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_rep_id");

                    b.Property<Guid?>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TratamentoRevogadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tratamento_revogado_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("text")
                        .HasColumnName("usuario_nome");

                    b.HasKey("Id")
                        .HasName("pk_tratamentos");

                    b.HasIndex("RegistroRepId")
                        .HasDatabaseName("ix_tratamentos_registro_rep_id");

                    b.HasIndex("TratamentoRevogadoId")
                        .HasDatabaseName("ix_tratamentos_tratamento_revogado_id");

                    b.HasIndex("TenantId", "FuncionarioId", "DataHora")
                        .HasDatabaseName("ix_tratamentos_tenant_id_funcionario_id_data_hora");

                    b.ToTable("tratamentos", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("boolean")
                        .HasColumnName("deve_trocar_senha");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<bool>("MfaHabilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_habilitado");

                    b.Property<string>("MfaSegredo")
                        .HasColumnType("text")
                        .HasColumnName("mfa_segredo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_falhas");

                    b.Property<DateTimeOffset?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.AssinaturaEspelho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTimeOffset>("AssinadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assinado_em");

                    b.Property<bool>("Concorda")
                        .HasColumnType("boolean")
                        .HasColumnName("concorda");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("HashEspelho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_espelho");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assinaturas_espelho");

                    b.HasIndex("FuncionarioId", "Ano", "Mes")
                        .IsUnique()
                        .HasDatabaseName("ix_assinaturas_espelho_funcionario_id_ano_mes");

                    b.ToTable("assinaturas_espelho", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.Atestado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnalisadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analisado_em");

                    b.Property<Guid?>("AnalisadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("analisado_por");

                    b.Property<Guid?>("ArquivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquivo_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int?>("MinutosParciais")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_parciais");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("ParecerRh")
                        .HasColumnType("text")
                        .HasColumnName("parecer_rh");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_atestados");

                    b.HasIndex("TenantId", "FuncionarioId", "DataInicio")
                        .HasDatabaseName("ix_atestados_tenant_id_funcionario_id_data_inicio");

                    b.ToTable("atestados", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.BancoHorasLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriadoPorNome")
                        .HasColumnType("text")
                        .HasColumnName("criado_por_nome");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("EstornaLancamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estorna_lancamento_id");

                    b.Property<Guid?>("FechamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fechamento_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_banco_horas");

                    b.HasIndex("TenantId", "FuncionarioId", "Data")
                        .HasDatabaseName("ix_banco_horas_tenant_id_funcionario_id_data");

                    b.ToTable("banco_horas", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.ConfiguracaoSeguranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AvaliacaoLgpdEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avaliacao_lgpd_em");

                    b.Property<string>("AvaliacaoLgpdResponsavel")
                        .HasColumnType("text")
                        .HasColumnName("avaliacao_lgpd_responsavel");

                    b.Property<bool>("ExigirDispositivoAutorizado")
                        .HasColumnType("boolean")
                        .HasColumnName("exigir_dispositivo_autorizado");

                    b.Property<bool>("FotoNaMarcacao")
                        .HasColumnType("boolean")
                        .HasColumnName("foto_na_marcacao");

                    b.Property<int>("RetencaoFotoDias")
                        .HasColumnType("integer")
                        .HasColumnName("retencao_foto_dias");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes_seguranca");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_configuracoes_seguranca_tenant_id");

                    b.ToTable("configuracoes_seguranca", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.DispositivoFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlteradoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("alterado_por");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("dispositivo_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<DateTimeOffset>("PrimeiroUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primeiro_uso");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UltimoUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso");

                    b.HasKey("Id")
                        .HasName("pk_dispositivos");

                    b.HasIndex("FuncionarioId", "DispositivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivos_funcionario_id_dispositivo_id");

                    b.ToTable("dispositivos", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.EscalaFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("Fim")
                        .HasColumnType("date")
                        .HasColumnName("fim");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<Guid>("JornadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("jornada_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_escalas");

                    b.HasIndex("FuncionarioId", "Inicio")
                        .IsUnique()
                        .HasDatabaseName("ix_escalas_funcionario_id_inicio");

                    b.ToTable("escalas", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.FechamentoPeriodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("DiasInconsistentes")
                        .HasColumnType("integer")
                        .HasColumnName("dias_inconsistentes");

                    b.Property<DateTimeOffset>("FechadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<Guid?>("FechadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("fechado_por");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<int>("MinutosAtrasos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_atrasos");

                    b.Property<int>("MinutosExtras")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_extras");

                    b.Property<int>("MinutosFaltas")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_faltas");

                    b.Property<int>("MinutosTrabalhados")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_trabalhados");

                    b.Property<DateTimeOffset?>("ReabertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reaberto_em");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fechamentos");

                    b.HasIndex("FuncionarioId", "Ano", "Mes")
                        .IsUnique()
                        .HasDatabaseName("ix_fechamentos_funcionario_id_ano_mes");

                    b.ToTable("fechamentos", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Abrangencia")
                        .HasColumnType("integer")
                        .HasColumnName("abrangencia");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_feriados");

                    b.HasIndex("TenantId", "Data")
                        .HasDatabaseName("ix_feriados_tenant_id_data");

                    b.ToTable("feriados", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.FotoMarcacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArquivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquivo_id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset?>("ExcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("excluida_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("RegistroRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_rep_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fotos_marcacao");

                    b.HasIndex("RegistroRepId")
                        .IsUnique()
                        .HasDatabaseName("ix_fotos_marcacao_registro_rep_id");

                    b.HasIndex("ExcluidaEm", "ExpiraEm")
                        .HasDatabaseName("ix_fotos_marcacao_excluida_em_expira_em");

                    b.ToTable("fotos_marcacao", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.PoliticaBancoHoras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<bool>("DescontarAtrasos")
                        .HasColumnType("boolean")
                        .HasColumnName("descontar_atrasos");

                    b.Property<bool>("ExtrasParaBanco")
                        .HasColumnType("boolean")
                        .HasColumnName("extras_para_banco");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ValidadeMeses")
                        .HasColumnType("integer")
                        .HasColumnName("validade_meses");

                    b.HasKey("Id")
                        .HasName("pk_politicas_banco_horas");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_politicas_banco_horas_tenant_id");

                    b.ToTable("politicas_banco_horas", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.RH.Domain.SolicitacaoCorrecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<TimeOnly?>("Horario")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("RegistroRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_rep_id");

                    b.Property<DateTimeOffset?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondido_em");

                    b.Property<Guid?>("RespondidoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("respondido_por");

                    b.Property<string>("RespostaRh")
                        .HasColumnType("text")
                        .HasColumnName("resposta_rh");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TratamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tratamento_id");

                    b.HasKey("Id")
                        .HasName("pk_solicitacoes");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_solicitacoes_funcionario_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_solicitacoes_tenant_id_status");

                    b.ToTable("solicitacoes", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.SaaS.Domain.AcessoSuporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_nome");

                    b.HasKey("Id")
                        .HasName("pk_acessos_suporte");

                    b.HasIndex("TenantId", "Inicio")
                        .HasDatabaseName("ix_acessos_suporte_tenant_id_inicio");

                    b.ToTable("acessos_suporte", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.SaaS.Domain.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BloqueioAutomatico")
                        .HasColumnType("boolean")
                        .HasColumnName("bloqueio_automatico");

                    b.Property<DateOnly?>("CanceladaEm")
                        .HasColumnType("date")
                        .HasColumnName("cancelada_em");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<decimal>("CustoMensal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("custo_mensal");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<int>("DiasParaBloqueio")
                        .HasColumnType("integer")
                        .HasColumnName("dias_para_bloqueio");

                    b.Property<int>("DiasTolerancia")
                        .HasColumnType("integer")
                        .HasColumnName("dias_tolerancia");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text")
                        .HasColumnName("fornecedor");

                    b.Property<int>("FuncionariosContratados")
                        .HasColumnType("integer")
                        .HasColumnName("funcionarios_contratados");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid?>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorMensal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_mensal");

                    b.HasKey("Id")
                        .HasName("pk_assinaturas");

                    b.HasIndex("Cnpj")
                        .HasDatabaseName("ix_assinaturas_cnpj");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("ix_assinaturas_plano_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_assinaturas_tenant_id");

                    b.ToTable("assinaturas", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.SaaS.Domain.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date")
                        .HasColumnName("competencia");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<DateOnly?>("PagaEm")
                        .HasColumnType("date")
                        .HasColumnName("paga_em");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_pago");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("pk_faturas");

                    b.HasIndex("TenantId", "Competencia")
                        .IsUnique()
                        .HasDatabaseName("ix_faturas_tenant_id_competencia");

                    b.ToTable("faturas", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.SaaS.Domain.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("LimiteFuncionarios")
                        .HasColumnType("integer")
                        .HasColumnName("limite_funcionarios");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteApp")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_app");

                    b.Property<bool>("PermiteTerminalWeb")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_terminal_web");

                    b.Property<decimal>("PrecoFuncionarioExcedente")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_funcionario_excedente");

                    b.Property<decimal>("PrecoMensal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_mensal");

                    b.HasKey("Id")
                        .HasName("pk_planos");

                    b.ToTable("planos", "personaliponto");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Estabelecimento", b =>
                {
                    b.HasOne("PersonaliPonto.Core.RepP.Domain.Empregador", "Empregador")
                        .WithMany()
                        .HasForeignKey("EmpregadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estabelecimentos_empregadores_empregador_id");

                    b.Navigation("Empregador");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.Funcionario", b =>
                {
                    b.HasOne("PersonaliPonto.Core.RepP.Domain.Estabelecimento", "Estabelecimento")
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_estabelecimentos_estabelecimento_id");

                    b.HasOne("PersonaliPonto.Core.RepP.Domain.Jornada", "Jornada")
                        .WithMany()
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_funcionarios_jornadas_jornada_id");

                    b.Navigation("Estabelecimento");

                    b.Navigation("Jornada");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.MarcacaoContexto", b =>
                {
                    b.HasOne("PersonaliPonto.Core.RepP.Domain.RegistroRep", null)
                        .WithMany()
                        .HasForeignKey("RegistroRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marcacoes_contexto_registros_rep_registro_rep_id");
                });

            modelBuilder.Entity("PersonaliPonto.Core.RepP.Domain.RegistroRep", b =>
                {
                    b.HasOne("PersonaliPonto.Core.RepP.Domain.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_rep_estabelecimentos_estabelecimento_id");

                    b.HasOne("PersonaliPonto.Core.RepP.Domain.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_registros_rep_funcionarios_funcionario_id");
                });

            modelBuilder.Entity("PersonaliPonto.Modules.SaaS.Domain.Assinatura", b =>
                {
                    b.HasOne("PersonaliPonto.Modules.SaaS.Domain.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assinaturas_planos_plano_id");

                    b.Navigation("Plano");
                });
#pragma warning restore 612, 618
        }
    }
}
