<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PersonaliPonto.Modules.RH\PersonaliPonto.Modules.RH.csproj" />
    <ProjectReference Include="..\PersonaliPonto.Modules.Analytics\PersonaliPonto.Modules.Analytics.csproj" />
    <ProjectReference Include="..\PersonaliPonto.Modules.SaaS\PersonaliPonto.Modules.SaaS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="SkiaSharp" Version="4.152.1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Documentos\Fontes\*.ttf" />
    <EmbeddedResource Include="Documentos\logo.png" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
